# NumPy kutubxonasiga doir bilimlaringizni mustaxkamlash uchun mashqlar

Hurmatli o'quvchi, bilimingizni yanada mustaxkamlashingiz va chuqurroq ko'nikmalarga ega bo'lishingiz uchun sizga topshiriqlar tayyorladik. Sizga yengillik yaratish maqsadida topshiriqni aynan qanday funksiyalar yordamida amalga oshirishingiz mumkin ekanini
 `💡Ishora` ko'rinishida yozdik!

#### 1. NumPy kutubxonasini `np` nomi ostida yuklang va numpy kutubxonasini chop eting.

versiya va konfiguratsiyani tekshiring.


`💡Ishora` import … as` and `np.__version__, np.show_config

In [1]:
import numpy as np

#### 2. Raqamli qiymatlar ro'yxatini bir o'lchovli NumPy massiviga aylantiring!

`💡Ishora` numpy.array

In [2]:
list_values = [1, 2, 3, 4, 5]
array = np.array(list_values)
array

array([1, 2, 3, 4, 5])

#### 3. Qiymatlari noldan iborat bo'lgan to'qqiz o'lchovli massiv yarating.



`💡Ishora` np.zeros

In [3]:
zero_array = np.zeros(9)
zero_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. Massiv yarating va uning xotira hajmini toping.



`💡Ishora` size, itemsize

In [9]:
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
array_itemsize = array.itemsize
array_size=array.size

#### 5. NumPy kutubxonasidagi add funksiyasi hujjatlarini buyruq satridan qanday olishi mumkin?


`💡Ishora` np.info

In [11]:
np.info()

 info(object=None, maxwidth=76, output=None, toplevel='numpy')

Get help information for an array, function, class, or module.

Parameters
----------
object : object or str, optional
    Input object or name to get information about. If `object` is
    an `ndarray` instance, information about the array is printed.
    If `object` is a numpy object, its docstring is given. If it is
    a string, available modules are searched for matching objects.
    If None, information about `info` itself is returned.
maxwidth : int, optional
    Printing width.
output : file like object, optional
    File like object that the output is written to, default is
    ``None``, in which case ``sys.stdout`` will be used.
    The object has to be opened in 'w' or 'a' mode.
toplevel : str, optional
    Start search at this level.

See Also
--------
source, lookfor

Notes
-----
When used interactively with an object, ``np.info(obj)`` is equivalent
to ``help(obj)`` on the Python prompt or ``obj?`` on the IPyth

#### 6. Shunday vekor yaratingki u o'n ikki o'lchamda va qiymatlari noldan iborat bo'lsin, lekin vektorning oltinchi qiymati 1 ga teng bo'lsin.



`💡Ishora` array[12]

In [13]:
array = np.zeros(12)
array[5] = 1
array

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.])

#### 7. Qiymatlari 20 dan 59 gacha bo'lgan vektor yarating.



`💡Ishora` arange

In [17]:
vector=np.arange(20,60)
vector

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58, 59])

#### 8. Vektor yarating va uni teskari o'zgartiring
(birinchi element oxirgisi bo'lsin)



`💡Ishora` array[::-1]

In [18]:
vector[::-1]

array([59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49, 48, 47, 46, 45, 44, 43,
       42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26,
       25, 24, 23, 22, 21, 20])

#### 9. 12 dan 20 gacha bo'lgan qiymatlarga ega 3x3 matritsa yarating.


`💡Ishora` reshape

In [19]:
values = np.random.randint(12, 21, size=9)
matrix = values.reshape(3, 3)
matrix

array([[20, 15, 12],
       [13, 12, 20],
       [18, 16, 19]])

#### 10. Quyidagi matritsadan foydalanib nolga teng bo'lmagan elementlarning indekslarini toping.
[3, 7, 0, 0, 9, 0]





`💡Ishora` np.nonzero

In [25]:
array=np.array([[3, 7, 0, 0, 9, 0]])
matrix=np.nonzero(array)
matrix

(array([0, 0, 0]), array([0, 1, 4]))

#### 11. Tasodifiy qiymatlar bilan 2x2x2 o'lchovidagi massiv yarating.


`💡Ishora` np.random.random

In [26]:
array_3d = np.random.random((2, 2, 2))
array_3d

array([[[0.34961993, 0.95239308],
        [0.58880668, 0.26098095]],

       [[0.95997289, 0.1079939 ],
        [0.53785362, 0.40992966]]])

#### 12. Tasodifiy sonlardan tashkil topgan 9X9 o'lchamidagi massiv yarating. So'ng uning eng katta va eng kichik qiymatlarini toping


`💡Ishora` min, max

In [30]:
values = np.random.random((9,9))
max_value = np.max(values)
min_value = np.min(values)
print(max_value)
print(min_value)

0.966036494416851
0.04534404040950413


#### 13. Quyidagi misol qanday natija beradi?


```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.7 == 7 * 0.1
```


`💡Ishora` NaN = not a number, inf = infinity

In [32]:
0 * np.nan  #Javob: nan
np.nan == np.nan #Javob:False
np.inf > np.nan #Javob:False
np.nan - np.nan #Javob:nan
np.nan in set([np.nan]) #Javob:True
0.7 == 7 * 0.1 #Javob:False

False

#### 14. O'lchamlari 6x3 va 3x4 bo'lgan martitsa yarating, so'ng ularning  ko'paytmasini hisoblang.



`💡Ishora` np.dot` or `np.ones

In [34]:
matrix_6_3 = np.random.random((6, 3))
matrix_3_4 = np.random.random((3, 4))
result = np.dot(matrix_6_3, matrix_3_4)
result

array([[1.09606574, 1.57656051, 0.9799556 , 0.63247436],
       [0.47455805, 0.97859246, 0.84803722, 0.50502729],
       [0.64014665, 1.39610997, 1.57676193, 1.05130932],
       [0.61150292, 0.70592917, 0.99513708, 0.88567232],
       [0.69581766, 1.55167042, 1.19969966, 0.62941533],
       [0.60231633, 1.1895986 , 1.01028037, 0.60867621]])

#### 15. Quyidagi misol qanday natija beradi?

```python
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [35]:
print(sum(range(5),-1))

9


In [36]:
from numpy import *
print(sum(range(5),-1))

10


#### 16. NumPy kutubxonasi yordamida ikkita massivni solishtiring va ular usida quyidagi amallarni bajaring.

```python
Array a: [1 2]
Array b: [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True True]
a <= b
[ True True]
```

In [39]:
a = np.array([1, 2])
b = np.array([4, 5])
print(a>b)
print(a>=b)
print(a<b)
print(a<=b)

[False False]
[False False]
[ True  True]
[ True  True]


#### 17. Quyidagi misol qanday natija beradi?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [44]:
np.array(0) / np.array(0) #Javob: nan
np.array(0) // np.array(0) #Javob: 0
np.array([np.nan]).astype(int).astype(float) #Javob: array([-9.22337204e+18])

<ipython-input-44-9679f0f24107>:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0) #Javob: nan
<ipython-input-44-9679f0f24107>:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0) #Javob: 0
<ipython-input-44-9679f0f24107>:3: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float) #Javob: array([-9.22337204e+18])


array([-9.22337204e+18])

#### 18. Ikkita massiv yarating va ular orasidagi umumiy qiymatlarni toping


`💡Ishora` np.intersect1d

In [45]:
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([4, 5, 6, 7, 8])
common_values = np.intersect1d(array1, array2)
common_values

array([4, 5])

#### 19. Tasodifiy sonlardan iborat bo'lgan massiv yarating, so'ng ularni quyida berilgan 4 xil usul yordamida musbat sonlarning butun qismini ajratib oling.

`💡Ishora` %, np.floor, astype, np.trunc

In [46]:
random_array = np.random.uniform(-10, 10, size=10)
positive_integers_mod = random_array[random_array > 0] % 1
positive_integers_floor = np.floor(random_array[random_array > 0])
positive_integers_astype = random_array[random_array > 0].astype(int)
positive_integers_trunc = np.trunc(random_array[random_array > 0])
print("Original array:", random_array)
print("Butun qismi % orqali:", positive_integers_mod)
print("Butun qismi np.floor orqali:", positive_integers_floor)
print("Butun qismi astype orqali:", positive_integers_astype)
print("Butun qismi np.trunc orqali:", positive_integers_trunc)

Original array: [-7.13891639e+00  4.36737516e+00 -2.02479746e+00 -8.62496396e+00
 -5.67762094e+00 -4.93894179e-03  3.17581624e+00 -5.03263117e+00
 -3.58978957e-01  6.79883882e+00]
Butun qismi % orqali: [0.36737516 0.17581624 0.79883882]
Butun qismi np.floor orqali: [4. 3. 6.]
Butun qismi astype orqali: [4 3 6]
Butun qismi np.trunc orqali: [4. 3. 6.]


#### 20. O'lchovlari 3x3 matritsa yarating, ularning qator qiymatlari 0 dan 2 gacha bo'lsin.



`💡Ishora` np.arange

In [49]:
matritsa = np.arange(9).reshape(3, 3)
matritsa

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 21. O'chamlari 10 bo'lgan tasodifiy vektor yarating va uni o'sish tartibida chiqaruvchi dastur tuzing.



`💡Ishora` sort

In [50]:
random_vector = np.random.random(10)
sorted_vector = np.sort(random_vector)
print("Tasodifiy vektor:", random_vector)
print("O'sish tartibida sortlangan vektor:", sorted_vector)

Tasodifiy vektor: [0.94321113 0.2358522  0.38469081 0.23046027 0.1350829  0.21931536
 0.62365927 0.28510151 0.52944141 0.41339907]
O'sish tartibida sortlangan vektor: [0.1350829  0.21931536 0.23046027 0.2358522  0.28510151 0.38469081
 0.41339907 0.52944141 0.62365927 0.94321113]


#### 22. Ikki tasodifiy A va B massiv yarating, ularning tengligini tekshiring

`💡Ishora` np.allclose, np.array_equal

In [52]:
A = np.random.random((3, 3))
B = np.random.random((3, 3))
equal_check_allclose = np.allclose(A, B)
equal_check_array_equal = np.array_equal(A, B)
print(equal_check_allclose)
print(equal_check_array_equal)

False
False


#### 23. O'lchamlari 6x3 va 3x4 matritsa tuzing va ularni o'zaro ko'paytiring.


`💡Ishora` np.dot or np.ones

In [53]:
matrix_a = np.random.random((6, 3))
matrix_b = np.random.random((3, 4))
result = np.dot(matrix_a, matrix_b)
result

array([[0.30006372, 0.33957962, 0.52450732, 0.49494181],
       [0.65749467, 0.69992608, 1.08842575, 1.00304885],
       [0.26360572, 0.54727296, 0.77950545, 0.73044106],
       [0.48286404, 0.85251786, 1.25803939, 1.30823353],
       [0.68492048, 0.71602619, 1.17689658, 1.42990899],
       [0.18600783, 0.25422495, 0.3452178 , 0.11842101]])

#### 24. Tasodifiy sonlardan iborat bo'lgan o'lchami 5 ga teng vektor yarating, so'ng uning eng katta qiymatini 0 ga o'zgartiring.


`💡Ishora` argmax

In [54]:
vector = np.random.random(5)
max_index = np.argmax(vector)
vector[max_index] = 0
vector

array([0.        , 0.04110115, 0.65452605, 0.33103677, 0.95963954])

#### 25. NumPy kutubxonasi yordamida kecha, bugun va ertangi kun sanalarini aniqlang.


`💡Ishora` np.datetime64, np.timedelta64

In [60]:
bugun = np.datetime64('today', 'D')
kecha = bugun - np.timedelta64(1, 'D')
ertaga = bugun + np.timedelta64(1, 'D')
print(f"Kecha:{kecha}")
print(f"Bugun:{bugun}")
print(f"Ertaga:{ertaga}")

Kecha:2024-10-22
Bugun:2024-10-23
Ertaga:2024-10-24


#### 26. 2016 yil yanvar oyiga to'g'ri keladigan barcha sanalarni NumPy kutubxonasi yordamida aniqlang.


`💡Ishora` np.arange(dtype=datetime64['D'])

In [62]:
start_date = np.datetime64('2016-01-01')
end_date = np.datetime64('2016-01-31')
january_dates = np.arange(start_date, end_date + np.timedelta64(1, 'D'), dtype='datetime64[D]')
print(january_dates)

['2016-01-01' '2016-01-02' '2016-01-03' '2016-01-04' '2016-01-05'
 '2016-01-06' '2016-01-07' '2016-01-08' '2016-01-09' '2016-01-10'
 '2016-01-11' '2016-01-12' '2016-01-13' '2016-01-14' '2016-01-15'
 '2016-01-16' '2016-01-17' '2016-01-18' '2016-01-19' '2016-01-20'
 '2016-01-21' '2016-01-22' '2016-01-23' '2016-01-24' '2016-01-25'
 '2016-01-26' '2016-01-27' '2016-01-28' '2016-01-29' '2016-01-30'
 '2016-01-31']


#### 27. 4 xil usul yordamida musbat sonlarning tasodifiy massivining butun son qismini ajratib oling.


`💡Ishora` %, np.floor, astype, np.trunc`

In [63]:
random_array = np.random.uniform(0, 10, size=10)
integer_part_mod = random_array[random_array > 0] % 1
integer_part_floor = np.floor(random_array[random_array > 0])
integer_part_astype = random_array[random_array > 0].astype(int)
integer_part_trunc = np.trunc(random_array[random_array > 0])

#### 28. Ixtiyoriy kichik massivlar yarating, ular yeg'indisini np.sum funksiyasidanda tezroq hisoblovchi dastur tuzing.


`💡Ishora` np.add.reduce

In [64]:
small_array1 = np.array([1, 2, 3])
small_array2 = np.array([4, 5, 6])
sum_using_np_sum = np.sum(small_array1) + np.sum(small_array2)
sum_using_np_add_reduce = np.add.reduce(small_array1) + np.add.reduce(small_array2)

#### 29. [1, 2, 3, 4, 5] vektor berilgan, har bir qiymat orasiga ketma-ket 3 ta nol raqamini yozuvchi dastur tuzing.


`💡Ishora` array[::4]

In [66]:
original_vector = np.array([1, 2, 3, 4, 5])
new_length = len(original_vector) + (len(original_vector) - 1) * 3
new_vector = np.zeros(new_length)
new_vector[::4] = original_vector
new_vector

array([1., 0., 0., 0., 2., 0., 0., 0., 3., 0., 0., 0., 4., 0., 0., 0., 5.])

#### 30. Quyidagi a massiv berilgan, a = [1,2,3,4,5,6,7,8,9,10,11,12,13,14] undan foydalangan holda siz quyidagi b massivni yarata olasizmi, b = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?


`💡Ishora` stride_tricks.as_strided

In [67]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])
b = np.lib.stride_tricks.as_strided(a, shape=(11, 4), strides=(a.itemsize, a.itemsize))
b

array([[ 1,  2,  3,  4],
       [ 2,  3,  4,  5],
       [ 3,  4,  5,  6],
       [ 4,  5,  6,  7],
       [ 5,  6,  7,  8],
       [ 6,  7,  8,  9],
       [ 7,  8,  9, 10],
       [ 8,  9, 10, 11],
       [ 9, 10, 11, 12],
       [10, 11, 12, 13],
       [11, 12, 13, 14]])

#### 31. Ixtiyoriy sonlardan tashkil topgan massiv yarating, unga o'xshash qiymatlar kiriting. So'ng, o'xshash qiymatlarni topuvchi dastur tuzing.


`💡Ishora` np.bincount, argmax

In [71]:
random_array = np.random.randint(0, 10, size=20)
counts = np.bincount(random_array)
most_common_value = np.argmax(counts)
most_common_count = counts[most_common_value]
print("Tasodifiy massiv:", random_array)
print("Eng ko'p uchragan qiymat:", most_common_value)
print("Uchragan soni:", most_common_count)

Tasodifiy massiv: [6 3 5 9 6 8 3 0 3 2 3 2 8 6 6 3 3 4 4 4]
Eng ko'p uchragan qiymat: 3
Uchragan soni: 6


#### BONUS!

`💡O'zingiz javob berishni istagan savolni kiriting va unga javob bering!`